# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gaussian mixture of regression models with contamination
#' 
#' Fast computation of simple regression slopes for each predictor represented by a column in a matrix
#'
#' Missing values (NA, Inf, NaN) are completely disregarded and pairwise complete cases are used for the analysis.
#' 
#' @param y A vector of outcomes.
#' @param X A design matrix of regressor variables. Must have the same number of rows as the length of y. 
#' @param maxit the maximum number of iterations to use for the EM algorithm
#' @param tol the tolerance used for determining convergence
#' @return A list with the variables: coefficients, stderr, and tstat that gives the slope estimate, the corresponding standard error, and their ratio for each column in x.
#' @author Claus Ekstrom <ekstrom@@sund.ku.dk>
#' @examples
#' x <- rnorm(1000)
#' y <- rnorm(1000, mean=c(x[1:700], rep(0, 300)), sd=rep(c(1,2), times=c(700,300)))
#' mgrwc(y, cbind(rep(1, 1000), x))
#'
#' @export
mgrwc <- function(y, X, maxit = 400L, tol = 1e-07) {
    .Call(`_mommix_mgrwc`, y, X, maxit, tol)
}

